#
# This file defines what provisioning porchlight entails
# 
---
- hosts: all
  gather_facts: False   # don't waste time gathering facts...go with what your gut tells you the server is!
  roles:
    - python27
    - pip
    - virtualenv
  tasks:
    - name: install python libraries
      yum: name={{item}}
      with_items:
        - libxml2-devel
        - libxml2-python
        - libxslt-devel
        - python-devel
      sudo: yes
    
    - name: create virtualenv (using python2.7)
      shell: virtualenv -p /usr/local/bin/python2.7 .env
      args:
        chdir: "{{project_path}}"
    
    - name: pip install requirements.txt
      pip: 
        chdir={{project_path}} 
        requirements=requirements.txt
        virtualenv={{project_path}}/.env
    
    - name: Run migrations
      django_manage: 
        command=migrate
        app_path={{project_path}}
        settings={{django_settings}}
        virtualenv={{project_path}}/.env